pipeline:
  name: aws_lambda_demo_v2
  identifier: aws_lambda_demo_v2
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githupharness
        repoName: AngelsTech/aws-lambda-demo
        build: <+input>
  stages:
    - stage:
        name: Build_and_Package
        identifier: Build_and_Package
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: eksconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          caching:
            enabled: false
          execution:
            steps:
              - step:
                  name: Install_Dependencies
                  identifier: Install_Dependencies
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: python:3.13
                    shell: Sh
                    command: |
                      echo "Installing Python dependencies..."
                      mkdir -p python
                      pip install -r devtest/requirements.txt -t python
                      zip -r layer_package.zip python
                      echo "Layer package created successfully"
                      ls -lh layer_package.zip
              - step:
                  name: Package_Lambda
                  identifier: Package_Lambda
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: python:3.13
                    shell: Sh
                    command: |
                      echo "Zipping Lambda function code..."
                      zip -r lambda_package.zip devtest \
                        -x "**/.git/*" \
                        -x "**/README.md" \
                        -x "**/Jenkinsfile" \
                        -x "**/__pycache__/*" \
                        -x "**/*.pyc"
                      echo "Lambda package contents:"
                      unzip -l lambda_package.zip
                      echo "Package size:"
                      ls -lh lambda_package.zip
              - step:
                  name: Upload_Artifacts_to_S3
                  identifier: Upload_Artifacts_to_S3
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      S3_BUCKET="harness-lambda-artifacts"  # Update with your S3 bucket
                      BUILD_ID="<+pipeline.executionId>"

                      echo "Uploading artifacts to S3..."
                      aws s3 cp layer_package.zip s3://$S3_BUCKET/$BUILD_ID/layer_package.zip
                      aws s3 cp lambda_package.zip s3://$S3_BUCKET/$BUILD_ID/lambda_package.zip

                      echo "Artifacts uploaded successfully"
                      echo "BUILD_ID=$BUILD_ID" >> build.env
                    outputVariables:
                      - name: BUILD_ID
                        type: String
                        value: BUILD_ID
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
    - stage:
        name: Deploy_Lambda
        identifier: Deploy_Lambda
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        spec:
          deploymentType: ServerlessAwsLambda
          service:
            serviceRef: <+input>
            serviceInputs:
              serviceDefinition:
                type: ServerlessAwsLambda
                spec:
                  variables: []
          environment:
            environmentRef: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: aws_lambda_infra
          execution:
            steps:
              - step:
                  name: Download_Artifacts_from_S3
                  identifier: Download_Artifacts_from_S3
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      S3_BUCKET="harness-lambda-artifacts"  # Update with your S3 bucket
                      BUILD_ID="<+pipeline.stages.Build_and_Package.spec.execution.steps.Upload_Artifacts_to_S3.output.outputVariables.BUILD_ID>"

                      echo "Downloading artifacts from S3..."
                      aws s3 cp s3://$S3_BUCKET/$BUILD_ID/layer_package.zip layer_package.zip
                      aws s3 cp s3://$S3_BUCKET/$BUILD_ID/lambda_package.zip lambda_package.zip

                      echo "Artifacts downloaded successfully"
                      ls -lh *.zip
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
              - step:
                  name: Publish_Lambda_Layer
                  identifier: Publish_Lambda_Layer
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      LAYER_NAME="hey-world-deps-<+env.name>"

                      echo "Publishing Lambda Layer: $LAYER_NAME"
                      LAYER_VERSION=$(aws lambda publish-layer-version \
                        --layer-name $LAYER_NAME \
                        --zip-file fileb://layer_package.zip \
                        --compatible-runtimes python3.13 \
                        --description "Dependencies for hey-world Lambda - <+env.name> environment" \
                        --query Version --output text)

                      echo "Layer version published: $LAYER_VERSION"
                      echo "LAYER_VERSION=$LAYER_VERSION" >> layer.env
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                    outputVariables:
                      - name: LAYER_VERSION
                        type: String
                        value: LAYER_VERSION
              - step:
                  name: Deploy_Lambda_Function
                  identifier: Deploy_Lambda_Function
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      FUNCTION_NAME="hey-world-demo-<+env.name>"
                      ZIP_FILE="lambda_package.zip"
                      LAYER_VERSION="<+pipeline.stages.Deploy_Lambda.spec.execution.steps.Publish_Lambda_Layer.output.outputVariables.LAYER_VERSION>"

                      # Determine IAM role based on environment
                      ROLE_ARN=""
                      if [ "<+env.name>" = "dev" ]; then
                        ROLE_ARN="arn:aws:iam::529088259986:role/lambda_exec_role_dev"
                      elif [ "<+env.name>" = "stage" ]; then
                        ROLE_ARN="arn:aws:iam::529088259986:role/lambda_exec_role_stage"
                      elif [ "<+env.name>" = "prod" ]; then
                        ROLE_ARN="arn:aws:iam::529088259986:role/lambda_exec_role_prod"
                      else
                        echo "ERROR: Unknown environment <+env.name>"
                        exit 1
                      fi

                      echo "Deploying Lambda function: $FUNCTION_NAME"

                      # Check if function exists
                      if ! aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
                        echo "Creating new Lambda function..."
                        aws lambda create-function \
                          --function-name $FUNCTION_NAME \
                          --runtime python3.13 \
                          --role $ROLE_ARN \
                          --handler devtest.function.lambda_handler \
                          --zip-file fileb://$ZIP_FILE \
                          --layers arn:aws:lambda:us-east-1:529088259986:layer:hey-world-deps-<+env.name>:$LAYER_VERSION \
                          --timeout 30 \
                          --memory-size 256 \
                          --description "Hey World Lambda function - <+env.name> environment"
                        
                        echo "Waiting for function to become active..."
                        aws lambda wait function-active --function-name $FUNCTION_NAME
                        echo "Function created successfully"
                      else
                        echo "Updating existing Lambda function..."
                        # Update function code
                        aws lambda update-function-code \
                          --function-name $FUNCTION_NAME \
                          --zip-file fileb://$ZIP_FILE
                        
                        echo "Waiting for function update to complete..."
                        aws lambda wait function-updated --function-name $FUNCTION_NAME
                        
                        # Update function configuration
                        aws lambda update-function-configuration \
                          --function-name $FUNCTION_NAME \
                          --layers arn:aws:lambda:us-east-1:529088259986:layer:hey-world-deps-<+env.name>:$LAYER_VERSION \
                          --timeout 30 \
                          --memory-size 256
                        
                        echo "Function updated successfully"
                      fi

                      # Get function ARN for output
                      FUNCTION_ARN=$(aws lambda get-function \
                        --function-name $FUNCTION_NAME \
                        --query 'Configuration.FunctionArn' \
                        --output text)

                      echo "Lambda function deployed: $FUNCTION_ARN"
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
              - step:
                  name: Setup_CloudWatch_Schedule
                  identifier: Setup_CloudWatch_Schedule
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      FUNCTION_NAME="hey-world-demo-<+env.name>"
                      RULE_NAME="hello-world-schedule-<+env.name>"
                      SCHEDULE="rate(5 minutes)"
                      STATEMENT_ID="cw-invoke-<+env.name>"

                      echo "Creating CloudWatch Events rule: $RULE_NAME"
                      aws events put-rule \
                        --name $RULE_NAME \
                        --schedule-expression "$SCHEDULE" \
                        --state ENABLED \
                        --description "Trigger hey-world Lambda every 5 minutes - <+env.name>"

                      # Get Lambda function ARN
                      FUNCTION_ARN=$(aws lambda get-function \
                        --function-name $FUNCTION_NAME \
                        --query 'Configuration.FunctionArn' \
                        --output text)

                      echo "Adding Lambda as target to CloudWatch rule..."
                      aws events put-targets \
                        --rule $RULE_NAME \
                        --targets "Id"="1","Arn"="$FUNCTION_ARN"

                      # Get rule ARN
                      SOURCE_ARN=$(aws events describe-rule \
                        --name $RULE_NAME \
                        --query 'Arn' \
                        --output text)

                      # Add permission for CloudWatch to invoke Lambda
                      echo "Granting CloudWatch permission to invoke Lambda..."
                      if ! aws lambda get-policy --function-name $FUNCTION_NAME 2>/dev/null | grep -q $STATEMENT_ID; then
                        aws lambda add-permission \
                          --function-name $FUNCTION_NAME \
                          --statement-id $STATEMENT_ID \
                          --action 'lambda:InvokeFunction' \
                          --principal events.amazonaws.com \
                          --source-arn $SOURCE_ARN
                        echo "Permission added successfully"
                      else
                        echo "Permission already exists, skipping..."
                      fi

                      echo "CloudWatch schedule setup complete"
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
              - step:
                  name: Test_Lambda_Function
                  identifier: Test_Lambda_Function
                  type: Run
                  spec:
                    connectorRef: eksconnector
                    image: amazon/aws-cli:2.15.0
                    shell: Sh
                    command: |
                      export AWS_DEFAULT_REGION=us-east-1
                      FUNCTION_NAME="hey-world-demo-<+env.name>"

                      echo "Testing Lambda function: $FUNCTION_NAME"
                      RESPONSE=$(aws lambda invoke \
                        --function-name $FUNCTION_NAME \
                        --payload '{}' \
                        --cli-binary-format raw-in-base64-out \
                        lambda-response.json)

                      echo "Invoke response:"
                      echo "$RESPONSE"

                      echo "Function output:"
                      cat lambda-response.json

                      # Check if invocation was successful
                      if echo "$RESPONSE" | grep -q '"StatusCode": 200'; then
                        echo "Lambda test successful!"
                      else
                        echo "Lambda test failed!"
                        exit 1
                      fi
                    envVariables:
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
            rollbackSteps: []
